" ~/.vimrc: Main Vim configuration file
" Cross-platform compatible for Linux, macOS, and Windows

" Compatibility & Encoding
set nocompatible              " Use Vim settings, not Vi
set encoding=utf-8            " UTF-8 encoding
set fileencoding=utf-8        " File encoding
scriptencoding utf-8

" Plugin Manager - vim-plug
" Auto-install vim-plug if not found
let data_dir = has('nvim') ? stdpath('data') . '/site' : '~/.vim'
if empty(glob(data_dir . '/autoload/plug.vim'))
  silent execute '!curl -fLo '.data_dir.'/autoload/plug.vim --create-dirs  https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim'
  autocmd VimEnter * PlugInstall --sync | source $MYVIMRC
endif

" Plugin declarations
call plug#begin('~/.vim/plugged')

" File navigation & fuzzy finding
Plug 'junegunn/fzf', { 'do': { -> fzf#install() } }
Plug 'junegunn/fzf.vim'
Plug 'preservim/nerdtree'
Plug 'ryanoasis/vim-devicons'

" Status line & appearance
Plug 'vim-airline/vim-airline'
Plug 'vim-airline/vim-airline-themes'
Plug 'morhetz/gruvbox'
Plug 'joshdick/onedark.vim'

" Git integration
Plug 'tpope/vim-fugitive'
Plug 'airblade/vim-gitgutter'

" Code completion & LSP
Plug 'neoclide/coc.nvim', {'branch': 'release'}
Plug 'github/copilot.vim'

" Syntax & language support
Plug 'sheerun/vim-polyglot'
Plug 'dense-analysis/ale'
Plug 'editorconfig/editorconfig-vim'

" Code navigation & editing
Plug 'preservim/nerdcommenter'
Plug 'tpope/vim-surround'
Plug 'jiangmiao/auto-pairs'
Plug 'easymotion/vim-easymotion'
Plug 'terryma/vim-multiple-cursors'

" Snippets
Plug 'SirVer/ultisnips'
Plug 'honza/vim-snippets'

" Utilities
Plug 'mbbill/undotree'
Plug 'christoomey/vim-tmux-navigator'

call plug#end()

" General Settings
set mouse=a                   " Enable mouse support
set clipboard=unnamedplus     " Use system clipboard
set backspace=indent,eol,start " Backspace behavior
set history=1000              " Command history
set undofile                  " Persistent undo
set undodir=~/.vim/undo       " Undo directory
set backup                    " Enable backups
set backupdir=~/.vim/backup   " Backup directory
set directory=~/.vim/swap     " Swap directory
set updatetime=300            " Faster updates
set timeoutlen=500            " Timeout for key combinations

" Create directories if they don't exist
if !isdirectory(expand(&undodir))
    call mkdir(expand(&undodir), "p")
endif
if !isdirectory(expand(&backupdir))
    call mkdir(expand(&backupdir), "p")
endif
if !isdirectory(expand(&directory))
    call mkdir(expand(&directory), "p")
endif

" UI & Appearance
set number                    " Show line numbers
set relativenumber            " Relative line numbers
set cursorline                " Highlight current line
set cursorlineopt=number      " Only highlight line number, not the whole line
set showcmd                   " Show command in status line
set showmode                  " Show current mode
set ruler                     " Show cursor position
set laststatus=2              " Always show status line
set showtabline=2             " Always show tab line
set signcolumn=yes            " Always show sign column
set scrolloff=8               " Lines to keep above/below cursor
set sidescrolloff=8           " Columns to keep left/right of cursor
set list                      " Show invisible characters
set listchars=tab:→\ ,trail:·,nbsp:␣,extends:⟩,precedes:⟨

" Terminal colors
if has('termguicolors')
    set termguicolors
endif

" Color scheme
syntax enable
set background=dark

" Use desert until plugins are installed, then switch to gruvbox
colorscheme desert
" silent! colorscheme gruvbox  " Uncomment after running :PlugInstall

" Custom highlight for cursorline - underline only
highlight CursorLine cterm=underline gui=underline ctermbg=NONE guibg=NONE
highlight CursorLineNr cterm=bold gui=bold ctermfg=Yellow guifg=Yellow

" Search Settings
set incsearch                 " Incremental search
set hlsearch                  " Highlight search results
set ignorecase                " Case-insensitive search
set smartcase                 " Case-sensitive if uppercase present
set wrapscan                  " Wrap search at EOF

" Indentation & Formatting
set autoindent                " Auto-indent new lines
set smartindent               " Smart indenting
set expandtab                 " Use spaces instead of tabs
set tabstop=4                 " Tab width
set shiftwidth=4              " Indent width
set softtabstop=4             " Backspace removes spaces
set shiftround                " Round indent to multiple of shiftwidth
filetype plugin indent on     " Enable filetype detection

" Code Folding
set foldenable                " Enable folding
set foldmethod=indent         " Fold based on indentation
set foldlevelstart=10         " Open most folds by default
set foldnestmax=10            " Max nested folds

" Completion & Wildmenu
set wildmenu                  " Enhanced command completion
set wildmode=longest:full,full
set wildignore+=*.o,*.obj,*.pyc,*.class,*.swp,*.zip
set wildignore+=*/tmp/*,*/node_modules/*,*/.git/*
set completeopt=menuone,noselect,preview

" Key Mappings
" Leader key
let mapleader = " "
let maplocalleader = ","

" Quick save & quit
nnoremap <leader>w :w<CR>
nnoremap <leader>q :q<CR>
nnoremap <leader>x :x<CR>
nnoremap <leader>Q :qa!<CR>

" Clear search highlighting
nnoremap <leader><space> :nohlsearch<CR>

" Window navigation
nnoremap <C-h> <C-w>h
nnoremap <C-j> <C-w>j
nnoremap <C-k> <C-w>k
nnoremap <C-l> <C-w>l

" Window resizing
nnoremap <leader>= <C-w>=
nnoremap <leader>+ :resize +5<CR>
nnoremap <leader>- :resize -5<CR>
nnoremap <leader>> :vertical resize +5<CR>
nnoremap <leader>< :vertical resize -5<CR>

" Buffer navigation
nnoremap <leader>bn :bnext<CR>
nnoremap <leader>bp :bprevious<CR>
nnoremap <leader>bd :bdelete<CR>
nnoremap <leader>bl :buffers<CR>

" Tab navigation
nnoremap <leader>tn :tabnew<CR>
nnoremap <leader>tc :tabclose<CR>
nnoremap <leader>to :tabonly<CR>
nnoremap <leader>1 1gt
nnoremap <leader>2 2gt
nnoremap <leader>3 3gt
nnoremap <leader>4 4gt
nnoremap <leader>5 5gt

" Move lines up/down
nnoremap <A-j> :m .+1<CR>==
nnoremap <A-k> :m .-2<CR>==
vnoremap <A-j> :m '>+1<CR>gv=gv
vnoremap <A-k> :m '<-2<CR>gv=gv

" Indent without losing selection
vnoremap < <gv
vnoremap > >gv

" Paste without yanking in visual mode
vnoremap p "_dP

" Better Y behavior (yank to end of line)
nnoremap Y y$

" Plugin Configuration - NERDTree
nnoremap <leader>n :NERDTreeToggle<CR>
nnoremap <leader>f :NERDTreeFind<CR>

let NERDTreeShowHidden=1
let NERDTreeQuitOnOpen=0
let NERDTreeMinimalUI=1
let NERDTreeDirArrows=1
let NERDTreeIgnore=['\.pyc$', '\.o$', '\.class$', '^__pycache__$']

" Auto-close if NERDTree is the only window
autocmd BufEnter * if tabpagenr('$') == 1 && winnr('$') == 1 && exists('b:NERDTree') && b:NERDTree.isTabTree() | quit | endif

" Plugin Configuration - FZF
nnoremap <leader>ff :Files<CR>
nnoremap <leader>fg :GFiles<CR>
nnoremap <leader>fb :Buffers<CR>
nnoremap <leader>fh :History<CR>
nnoremap <leader>fl :Lines<CR>
nnoremap <leader>ft :Tags<CR>
nnoremap <leader>fc :Commands<CR>
nnoremap <leader>fr :Rg<CR>

" FZF window layout
let g:fzf_layout = { 'down': '40%' }
let g:fzf_preview_window = ['right:50%', 'ctrl-/']

" Plugin Configuration - Airline
let g:airline_powerline_fonts = 1
let g:airline_theme = 'gruvbox'
let g:airline#extensions#tabline#enabled = 1
let g:airline#extensions#tabline#formatter = 'unique_tail'
let g:airline#extensions#branch#enabled = 1
let g:airline#extensions#ale#enabled = 1

" Plugin Configuration - CoC (Code Completion)
" Install extensions
let g:coc_global_extensions = [
    \ 'coc-json',
    \ 'coc-tsserver',
    \ 'coc-html',
    \ 'coc-css',
    \ 'coc-pyright',
    \ 'coc-sh',
    \ 'coc-snippets',
    \ 'coc-pairs',
    \ ]

" Use tab for trigger completion (compatible with older CoC versions)
function! CheckBackspace() abort
  let col = col('.') - 1
  return !col || getline('.')[col - 1]  =~# '\s'
endfunction

" Check if CoC is loaded
function! s:check_coc_loaded()
  return exists('g:did_coc_loaded') || exists('*CocAction')
endfunction

" Tab completion - works with both old and new CoC versions
inoremap <silent><expr> <TAB>
      \ pumvisible() ? "\<C-n>" :
      \ CheckBackspace() ? "\<TAB>" :
      \ <SID>check_coc_loaded() ? coc#refresh() : "\<C-n>"
inoremap <expr><S-TAB> pumvisible() ? "\<C-p>" : "\<C-h>"

" Make <CR> to accept selected completion item or notify coc.nvim to format
" Safe version that works without CoC
inoremap <silent><expr> <CR> pumvisible() ? "\<C-y>" : "\<C-g>u\<CR>"

" Use <c-space> to trigger completion (only if CoC is loaded)
if has('nvim')
  inoremap <silent><expr> <c-space> <SID>check_coc_loaded() ? coc#refresh() : "\<C-x>\<C-o>"
else
  inoremap <silent><expr> <c-@> <SID>check_coc_loaded() ? coc#refresh() : "\<C-x>\<C-o>"
endif

" GoTo code navigation (only map if CoC is available)
if <SID>check_coc_loaded()
  nmap <silent> gd <Plug>(coc-definition)
  nmap <silent> gy <Plug>(coc-type-definition)
  nmap <silent> gi <Plug>(coc-implementation)
  nmap <silent> gr <Plug>(coc-references)
endif

" Show documentation
nnoremap <silent> K :call ShowDocumentation()<CR>

function! ShowDocumentation()
  if <SID>check_coc_loaded() && CocAction('hasProvider', 'hover')
    call CocActionAsync('doHover')
  elseif &filetype == 'vim'
    execute 'h '.expand('<cword>')
  else
    execute '!' . &keywordprg . " " . expand('<cword>')
  endif
endfunction

" Rename symbol (only if CoC is loaded)
if <SID>check_coc_loaded()
  nmap <leader>rn <Plug>(coc-rename)
  nmap <leader>fmt <Plug>(coc-format)
  xmap <leader>fmt <Plug>(coc-format-selected)
  nmap <leader>qf <Plug>(coc-fix-current)
endif

" Highlight the symbol and its references when holding the cursor (safe version)
augroup CocHighlight
  autocmd!
  autocmd CursorHold * if <SID>check_coc_loaded() | silent call CocActionAsync('highlight') | endif
augroup END

" Plugin Configuration - ALE (Linting)
let g:ale_linters = {
\   'python': ['flake8', 'pylint'],
\   'javascript': ['eslint'],
\   'typescript': ['eslint', 'tsserver'],
\   'sh': ['shellcheck'],
\}

let g:ale_fixers = {
\   '*': ['remove_trailing_lines', 'trim_whitespace'],
\   'python': ['black', 'isort'],
\   'javascript': ['prettier', 'eslint'],
\   'typescript': ['prettier', 'eslint'],
\   'css': ['prettier'],
\   'html': ['prettier'],
\}

let g:ale_fix_on_save = 1
let g:ale_sign_error = '✗'
let g:ale_sign_warning = '⚠'

" Plugin Configuration - GitGutter
let g:gitgutter_enabled = 1
let g:gitgutter_map_keys = 0
nmap <leader>gn <Plug>(GitGutterNextHunk)
nmap <leader>gp <Plug>(GitGutterPrevHunk)
nmap <leader>gs <Plug>(GitGutterStageHunk)
nmap <leader>gu <Plug>(GitGutterUndoHunk)

" Plugin Configuration - NERDCommenter
let g:NERDSpaceDelims = 1
let g:NERDCompactSexyComs = 1
let g:NERDDefaultAlign = 'left'
let g:NERDCommentEmptyLines = 1
let g:NERDTrimTrailingWhitespace = 1

" Plugin Configuration - UndoTree
nnoremap <leader>u :UndotreeToggle<CR>

" Language-Specific Settings
" Python
autocmd FileType python setlocal expandtab shiftwidth=4 tabstop=4 softtabstop=4

" JavaScript/TypeScript
autocmd FileType javascript,typescript,javascriptreact,typescriptreact setlocal expandtab shiftwidth=2 tabstop=2 softtabstop=2

" HTML/CSS
autocmd FileType html,css,scss setlocal expandtab shiftwidth=2 tabstop=2 softtabstop=2

" Shell scripts
autocmd FileType sh,bash setlocal expandtab shiftwidth=2 tabstop=2 softtabstop=2

" Markdown
autocmd FileType markdown setlocal wrap linebreak nolist textwidth=0 wrapmargin=0

" JSON
autocmd FileType json setlocal expandtab shiftwidth=2 tabstop=2 softtabstop=2

" Auto Commands
" Return to last edit position when opening files
autocmd BufReadPost *
    \ if line("'\"") > 0 && line("'\"") <= line("$") |
    \   exe "normal! g`\"" |
    \ endif

" Auto-reload vimrc on save
autocmd BufWritePost ~/.vimrc,~/.vim/vimrc source %

" Trim trailing whitespace on save
autocmd BufWritePre * %s/\s\+$//e

" Highlight yanked text
if has('nvim')
    autocmd TextYankPost * silent! lua vim.highlight.on_yank {higroup="IncSearch", timeout=200}
endif

" Custom Commands
" Quick edit vimrc
command! Vimrc :e $MYVIMRC

" Source vimrc
command! Source :source $MYVIMRC

" Install plugins
command! PlugInstall :PlugInstall

" Update plugins
command! PlugUpdate :PlugUpdate

" Clean plugins
command! PlugClean :PlugClean

" Local Configuration
" Source local vimrc if it exists (machine-specific settings)
if filereadable(expand("~/.vimrc.local"))
    source ~/.vimrc.local
endif

" Text objects for brackets and quotes (enhance visual selection)
" These work in visual and operator-pending modes
" Select inside brackets: vib, vi(, vi{, vi[, vi<
" Select around brackets: vab, va(, va{, va[, va<
" Select inside quotes: vi", vi', vi`
" Select around quotes: va", va', va`

" Quick bracket selection in visual mode
xnoremap aS a<

" Jump between matching brackets
nnoremap <leader>% %
vnoremap <leader>% %
xnoremap as a[
xnoremap aS a<

" Jump between matching brackets
nnoremap <leader>% %
vnoremap <leader>% %
